### ISSUE TITLE
Tests

### ISSUE THREAD

**Issue by jayvdb** [prahladyeri/pipshow#4]
In order to validate my rpm package, some sort of offline tests are needed.
https://build.opensuse.org/package/show/home:jayvdb:py-new/python-pipshow
Typical approach for pip tools is to use a fake pypi server, such as devpi.

**Comment by jayvdb** [comment]
Note https://github.com/prahladyeri/pipshow/commit/9b1332c19d511bdb684c73843e12c32511eca730 was py2 incompatible.  I dont know if the package was already incompatible, but my invocation of `pipshow --help` started failing with 1.0.6

**Comment by prahladyeri** [comment]
This is fixed in latest version (1.0.7), please test and let me know.
